// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID      int64
	UserID  pgtype.Int8
	Title   string
	Content pgtype.Text
	Created pgtype.Timestamptz
}

type User struct {
	ID   int64
	Sub  string
	Name string
}
